name: nfc_writter
description: nfc_writter_by_dnmlnk
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  nfc_manager: ^3.2.0

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
